# clean base image containing only comfyui, comfy-cli and comfyui-manager
FROM runpod/worker-comfyui:5.8.4-base

# build-time tokens for gated downloads — never baked into final image.
# pass via: docker build --build-arg HF_TOKEN=$HF_TOKEN ...
ARG HF_TOKEN=""

# install custom nodes into comfyui
RUN comfy node install --exit-on-fail comfyui-kjnodes@1.1.7 --mode remote || (echo "WARN: comfyui-kjnodes@1.1.7 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-kjnodes --mode remote)
RUN comfy node install --exit-on-fail comfyui_controlnet_aux@1.1.2 || (echo "WARN: comfyui_controlnet_aux@1.1.2 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui_controlnet_aux)
RUN comfy node install --exit-on-fail gguf@2.3.6 || (echo "WARN: gguf@2.3.6 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail gguf)
RUN comfy node install --exit-on-fail rgthree-comfy
RUN git clone https://github.com/o-l-l-i/ComfyUI-Olm-DragCrop /comfyui/custom_nodes/ComfyUI-Olm-DragCrop

# download models into comfyui
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors' --relative-path models/text_encoders --filename 'qwen/qwen_2.5_vl_7b_fp8_scaled.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors' --relative-path models/vae --filename 'qwen/qwen_image_vae.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/yzd-v/DWPose/yolox_l.onnx' --relative-path models/annotators --filename 'yolox_l.onnx' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/hr16/DWPose-TorchScript-BatchSize5/resolve/main/dw-ll_ucoco_384_bs5.torchscript.pt' --relative-path models/annotators --filename 'dw-ll_ucoco_384_bs5.torchscript.pt' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Lightning-4steps-V2.0.safetensors' --relative-path models/loras --filename 'qwen/Qwen-Image-Lightning-4steps-V2.0.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/peteromallet/Qwen-Image-Edit-InSubject/resolve/main/InSubject-0.5.safetensors' --relative-path models/loras --filename 'qwen/InSubject-0.5.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/kudzueye/boreal-qwen-image/resolve/main/qwen-boreal-general-discrete-low-rank.safetensors' --relative-path models/loras --filename 'qwen/qwen-boreal-general-discrete-low-rank.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/TheMindExpansionNetwork/special-loras/resolve/main/251018_MICKMUMPITZ_QWEN-EDIT_360_03.safetensors' --relative-path models/loras --filename 'qwen/251018_MICKMUMPITZ_QWEN-EDIT_360_03.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/lovis93/next-scene-qwen-image-lora-2509/resolve/main/next-scene_lora-v2-3000.safetensors' --relative-path models/loras --filename 'qwen/next-scene_lora-v2-3000.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/prithivMLmods/Qwen-Image-Studio-Realism/resolve/main/qwen-studio-realism.safetensors' --relative-path models/loras --filename 'qwen/qwen-studio-realism.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/QuantStack/Qwen-Image-Edit-2509-GGUF/resolve/main/Qwen-Image-Edit-2509-Q5_0.gguf' --relative-path models/diffusion_models --filename 'gguf/Qwen-Image-Edit-2509-Q5_0.gguf' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done

# copy all input data (like images or videos) into comfyui (uncomment and adjust if needed)
# COPY input/ /comfyui/input/

# user-provided inputs override the auto-generated placeholders above.
RUN wget --progress=dot:giga -O '/comfyui/input/a_candid_portrait_of_a_woman_with_natural_makeup_showcasing_her_unique_facial_features_captured_in__5837qamrn99y6vyf1nee_2.jpg' "https://cool-anteater-319.convex.cloud/api/storage/0dcc25af-bb4f-4fbd-80c6-33154b00398b"
RUN wget --progress=dot:giga -O '/comfyui/input/a_unique-looking_fashion_model_with_distinct_facial_features_medium_close-up_shot_professional_stud_6dyrfa5j5bs6mo5guhf3_1.jpg' "https://cool-anteater-319.convex.cloud/api/storage/e809c1c6-2f97-467a-8010-c509024735fb"
RUN wget --progress=dot:giga -O '/comfyui/input/a_cozy_modern_five_star_restaurant_with_glass_windows_overlooking_a_foggy_pine_forest_natural_mount_k69q6wfb2faiwi2cx42s_0.jpg' "https://cool-anteater-319.convex.cloud/api/storage/cee289f3-3d52-4478-8649-1e60a9f99537"
RUN wget --progress=dot:giga -O '/comfyui/input/istockphoto-1369129270-612x612.jpg' "https://cool-anteater-319.convex.cloud/api/storage/15145dc9-3174-4e0d-9719-2937e7a823ea"
